stages:
  - test

variables:
  SOLUTION_PATH: backend/Solution.sln

before_script:
  - 'dotnet restore $SOLUTION_PATH'

test:
  stage: test
  script:
    - 'dotnet test $SOLUTION_PATH'

image:
  name: mcr.microsoft.com/dotnet/sdk:latest
