stages:
  - publish

variables:
  DOTNET_VERSION: '6.0.x'

before_script:
  - 'which dotnet || (curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version $DOTNET_VERSION)'
  - export PATH="$HOME/.dotnet:$PATH"

publish:
  stage: publish
  script:
    - cd ./backend
    - dotnet restore Solution.sln
    - dotnet build Solution.sln --configuration Release
    - dotnet publish Solution.sln --configuration Release
