stages:
  - test

variables:
  SOLUTION_PATH: backend

before_script:
  - 'dotnet restore backend/Solution.sln'

test:
  stage: test
  only:
    - main
  script:
    - 'dotnet test backend/Solution.sln'
