stages:
  - test

variables:
  SOLUTION_PATH: backend/ExpenseTrackerApi/Solution.sln

before_script:
  - 'dotnet restore $SOLUTION_PATH'

test:
  stage: test
  script:
    - 'dotnet test $SOLUTION_PATH'
  only:
    - branches
  except:
    - master

image:
  name: mcr.microsoft.com/dotnet/sdk:latest
