stages:
  - test
  - build_frontend

variables:
  SOLUTION_PATH_BACKEND: "backend/Solution.sln"
  SOLUTION_PATH_FRONTEND: "frontend"

image:
  name: mcr.microsoft.com/dotnet/sdk:latest

before_script:
  - 'apt-get update -qy && apt-get install -y nodejs npm'

test_backend:
  stage: test
  only:
    - main
  script:
    - 'cd $SOLUTION_PATH_BACKEND'
    - 'dotnet restore'
    - 'dotnet test'

build_frontend:
  stage: build_frontend
  only:
    - main
  script:
    - 'cd $SOLUTION_PATH_FRONTEND'
    - 'npm install'
    - 'npm run build'
  dependencies:
    - test_backend 