stages:
  - test

variables:
  SOLUTION_PATH_BACKEND: "backend/Solution.sln"
  SOLUTION_PATH_FRONTEND: "frontend"

image:
  name: mcr.microsoft.com/dotnet/sdk:latest

before_script:
  - 'dotnet restore $SOLUTION_PATH_BACKEND'
  - 'cd $SOLUTION_PATH_FRONTEND && npm install'

test:
  stage: test
  only:
    - main
  script:
    - 'dotnet test $SOLUTION_PATH_BACKEND'
    - 'cd $SOLUTION_PATH_FRONTEND && npm run build'
  artifacts:
    paths:
      - frontend/dist/
