# stages:
#   - test

# variables:
#   SOLUTION_PATH: backend/Solution.sln

# before_script:
#   - 'dotnet restore $SOLUTION_PATH'

# test:
#   stage: test
#   script:
#     - 'dotnet test $SOLUTION_PATH'

# image:
#   name: mcr.microsoft.com/dotnet/sdk:latest


name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/Solution.sln

      - name : Build
        run: dotnet build ./backend/Solution.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./backend/Solution.sln --configuration Release --no-build