version: '3.8'

services:
  expense-tracker-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: expense_tracker_database
      MYSQL_ROOT_PASSWORD: Expense.tracker.password_2024!
    ports:
      - "3306:3306"
